# Change these first
owner: guanguans # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Guanguans Blog
    url: https://www.guanguans.cn
  - name: Github Pages
    url: https://guanguans.github.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Guanguans Blog
  introTitle: "**Guanguans Blog**"
  introMessage: This is a sample status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "0 */1 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
